config/routes.rb
Volunteer::Application.routes.draw do
  mount Mercury::Engine => '/'

  devise_for :users

  root :to => "index#index"
  resources :projects do
    member { put :mercury_update }
    collection { get :search }
  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  belongs_to :user
  validates :description, :title, :user, :presence => true
  attr_accessible :description, :title, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  has_many :projects
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  def page_title
    "Volunteer Finder"
  end
  helper_method :page_title
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def index
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_filter :authenticate_user!
  def new
    @project = Project.new(params[:project])
  end
  def index
    @projects = Project.all
  end
  def create
    @project = Project.create(params[:project].merge(:user_id => current_user.id))
    if @project.persisted?
      flash[:success] = "Project Created"
      redirect_to project_path(@project)
    else
      flash[:danger] = @project.errors.full_messages.join("<br>")
      render :action => :new
    end
  end
  def show
    @project = Project.find(params[:id])
  end

  def search
    query = params[:q]
    @results = Project.where("title LIKE ? OR description LIKE ?","%#{query}%", "%#{query}%")
  end

  def mercury_update
    @project = Project.find(params[:id])
    if @project.user != current_user
      render :text => "Unauthorized"
    end
    %w{information title description}.each do |value|
      @project.send("#{value}=",params[:content]["project_#{value}".to_sym][:value])
    end
    @project.save!
    render text: ""
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/_flashes.html.erb
<div id="flash">
  <% flash.each do |key, value| -%>
    <div id="flash_<%= key %>" class="alert alert-<%= key %>" style="text-align:center;"><%= raw value %></div>
  <% end -%>
</div>

app/views/application/_footer.html.erb
Created by Team Colossus for CS 361 at Oregon State University.

app/views/application/_javascript.html.erb
<%= javascript_include_tag :application %>

<%= yield :javascript %>

app/views/application/_jumbotron.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>Welcome!</h1>
    <p>Ever wanted to volunteer your time, but didn't have the financial means to do so? Always wanted to be a part of
      a volunteer effort, but don't have the time to do so yourself? Join us at Volunteer Finder and we'll match those
      who have time to give with donors who are excited to be a part of helping improve the world!</p>
    <p><%= link_to "Register now »", new_user_registration_path, :class => "btn btn-primary btn-lg", :role => "button" %></p>
  </div>
</div>

app/views/application/_logged_in_jumbotron.erb
<div class="jumbotron">
  <div class="container" style="text-align: center;">
    <h1>Get Started</h1>
    <p>What would you like to do?</p>
    <div class="row">
      <div class="col-lg-6" style="text-align:center;">
        <a class="btn btn-primary btn-lg" role="button" href="<%= new_project_path %>">Create Project</a>
      </div>
      <div class="col-lg-6" style="text-align:center;">
        <%= link_to "Browse Projects", projects_path, :class => "btn btn-primary btn-lg", :role => "button" %>
      </div>
    </div>
  </div>
</div>

app/views/application/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Volunteer Finder</a>
    </div>
    <form class="navbar-form navbar-left" action="<%= search_projects_path %>">
      <div class="form-group">
        <input type="text" placeholder="Search Projects" class="form-control" name="q">
      </div>
    </form>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li class="navbar-text">Logged in as <%= current_user.email %></li>
          <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Register", new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</div>

app/views/index/index.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Become a Donor!</h2>
    <p>Join as a donor today and help volunteers live their dream of helping others! Watch their progress and see
      what you helped make happen unfold.
    </p>
  </div>
  <div class="col-md-6">
    <h2>Become a Volunteer!</h2>
    <p>Want to build houses for the poor? Feed the homeless? Come together as a community and provide technology or
       other opportunities to the less fortunate in undeveloped nations? If you have the drive but not the funds then
       join us as a volunteer, post your project, and get help from donors!
    </p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8" />
    <meta name="ROBOTS" content="NOODP" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= page_title %></title>
    <%= stylesheet_link_tag :application, :media => 'all' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%= render :partial => "application/navbar" %>
    <% if params[:controller] == "index" %>
      <% if user_signed_in? %>
        <%= render :partial => "application/logged_in_jumbotron" %>
      <% else %>
        <%= render(:partial => "application/jumbotron") %>
      <% end %>
    <% end %>
    <div id="main" class="container">
      <%= render 'flashes' -%>
      <%= yield %>
      <footer>
        <%= render :partial => "application/footer" %>
      </footer>
    </div>
    <%= render 'javascript' %>
  </body>
</html>

app/views/layouts/mercury.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, maximum-scale=1.0, initial-scale=1.0">
    <%= csrf_meta_tags %>
    <title>Mercury Editor</title>
    <%= stylesheet_link_tag    'mercury' %>
    <%= javascript_include_tag 'mercury' %>
  </head>
  <body>
    <script type="text/javascript">
      // Set to the url that you want to save any given page to, leave null for default handling.
      var saveUrl = null;

      // Instantiate the PageEditor
      new Mercury.PageEditor(saveUrl, {
        saveStyle:  'form', // 'form', or 'json' (default json)
        saveMethod: null, // 'PUT', or 'POST', (create, vs. update -- default PUT)
        visible:    true  // boolean - if the interface should start visible or not
      });
    </script>
  </body>
</html>

app/views/projects/index.html.erb
<table class="table table-bordered table-striped">
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @projects.each do |project| %>
    <tr>
      <td><%= link_to project.title, project_path(project) %></td>
      <td><%= project.description %></td>
    </tr>
  <% end %>
</table>

app/views/projects/new.html.erb
<div class="new-project" class="container" style="text-align: center;">
  <h2>Create a New Project</h2>
  <%= simple_form_for @project, :html => {:class => 'form-inline'} do |f| %>
    <%= f.input :title %>
    <%= f.input :description %>
    <%= f.submit %>
  <% end %>
</div>

app/views/projects/search.html.erb
<h1 style="text-align:center;">Search Results</h1>
<table class="table table-bordered table-striped">
  <tr>
    <th>Title</th>
    <th>Description</th>
  </tr>
  <% @results.each do |project| %>
    <tr>
      <td><%= link_to project.title, project_path(project) %></td>
      <td><%= project.description %></td>
    </tr>
  <% end %>
</table>

app/views/projects/show.html.erb
<div class="row" style="text-align:center;">
  <h2 id="project_title" data-mercury="simple" data-type="editable"><%= @project.title %></h2>
  <p id="project_description" data-mercury="simple" data-type="editable"><%= @project.description %></p>
  <% if @project.user == current_user %>
    <%= link_to "Edit Project", "/editor" + request.path, :id => "edit_link", :class => "btn btn-primary btn-sm", :data => {:save_url => mercury_update_project_path(@project)} %>
  <% end %>
</div>
<div class="row">
  <h1 style="text-align: center;">Information</h1>
  <span id="project_information" data-mercury="full" data-type="editable" style="text-align: center;display:block;">
    <%= raw @project.information %>
  </span>
</div>